import type { Metadata } from 'next'
import { notFound } from 'next/navigation'
import Link from 'next/link'
import { KnowledgeHeader } from '@/components/knowledge/research-index'
import { FrontierBreadcrumb, FrontierShell } from '@/components/frontier-shell'
import { projects, research } from '@/lib/knowledge'
export function generateStaticParams() { return projects.map((project) => ({ slug: project.slug })) }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const project = projects.find((entry) => entry.slug === slug); return project ? { title: `${project.name} | AKSOS`, description: project.description } : {} }
export default async function ProjectDetailPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const project = projects.find((entry) => entry.slug === slug); if (!project) notFound(); const items = research.filter((item) => project.relatedResearch.includes(item.id)); return <FrontierShell><FrontierBreadcrumb items={[{ label: 'FRONTIER', href: '/research' }, { label: 'Projects', href: '/projects/batana' }, { label: project.name }]} /><main><KnowledgeHeader eyebrow="Knowledge / Project" title={project.name} description={project.description} /><section className="mx-auto max-w-6xl px-6 pb-24 md:px-10"><div className="grid gap-12 md:grid-cols-[0.8fr_1.2fr]"><div><p className="font-mono text-xs uppercase tracking-[0.18em] text-muted-foreground">Research questions</p><ul className="mt-6 flex flex-col gap-5">{project.researchQuestions.map((question) => <li key={question} className="border-l border-border pl-5 text-lg leading-7">{question}</li>)}</ul></div><div><p className="font-mono text-xs uppercase tracking-[0.18em] text-muted-foreground">Connected research</p><div className="mt-6 grid gap-px border border-border bg-border">{items.length ? items.map((item) => <Link key={item.id} href={`/research/${item.slug}`} className="bg-background p-6 hover:bg-muted/40">{item.question}</Link>) : <p className="bg-background p-6 text-muted-foreground">This project is currently presented through its primary project page.</p>}</div></div></div></section></main></FrontierShell> }
