import Image from 'next/image'
import Link from 'next/link'
import { SiteFooter } from '@/components/site-footer'
import { SiteHeader } from '@/components/site-header'

const HEADSHOT_URL = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/bnw%20headshot-HyAFeyny9huyy7USylb5BN2myAe3A3.jpg'
const tinoLinkedInUrl = process.env.NEXT_PUBLIC_TINO_LINKEDIN_URL

function Label({ children }: { children: React.ReactNode }) {
  return <p className="font-mono text-[11px] uppercase tracking-[0.2em] text-muted-foreground">{children}</p>
}

function Rule() { return <div className="h-px w-full bg-border/70" aria-hidden="true" /> }

function ProblemDiagram() {
  const terms = ['INFORMATION', 'REGULATION', 'PROJECT', 'ORGANIZATION', 'FUNDING', 'PEOPLE', 'INFRASTRUCTURE']
  return <figure className="border-y border-border/70 py-10 md:py-14" aria-labelledby="problem-caption">
    <div className="grid gap-8 md:grid-cols-[1fr_auto_1fr] md:items-center">
      <div className="grid grid-cols-2 gap-x-6 gap-y-4 font-mono text-[11px] tracking-[0.16em] text-muted-foreground sm:grid-cols-3 md:grid-cols-2">
        {terms.map((term) => <span key={term} className="border-b border-border/50 pb-2">{term}</span>)}
      </div>
      <div className="flex flex-col items-center gap-3 text-muted-foreground" aria-hidden="true"><div className="h-16 w-px bg-border" /><span className="text-xl">↓</span><span className="font-mono text-xs">???</span><div className="h-16 w-px bg-border" /><span className="text-xl">↓</span></div>
      <div id="problem-caption" className="flex flex-col gap-4 font-mono text-[11px] uppercase tracking-[0.16em] text-muted-foreground"><span>WHO IS CONNECTED?</span><span>WHAT CHANGED?</span><span>WHO IS AFFECTED?</span><span>WHAT IS MISSING?</span><span>WHERE IS THE POSSIBILITY?</span><strong className="pt-4 text-foreground">UNDERSTANDING</strong></div>
    </div>
    <figcaption className="sr-only">Information and entities become more useful when their relationships lead to understanding.</figcaption>
  </figure>
}

function OutcomesDiagram() {
  return <figure className="border-y border-border/70 py-10" aria-labelledby="outcomes-caption">
    <div className="mx-auto flex max-w-3xl flex-col items-center text-center font-mono text-[11px] uppercase tracking-[0.14em]">
      <strong className="border border-foreground px-5 py-3 text-foreground">AKSOS</strong><span className="h-8 w-px bg-border" /><span className="border border-border px-5 py-3">CONNECTED UNDERSTANDING</span><span className="h-8 w-px bg-border" />
      <div className="grid w-full gap-8 md:grid-cols-2"><div className="border-t border-foreground pt-5"><strong className="text-foreground">BUILD CAPACITY</strong><p className="mt-4 text-left normal-case leading-6 tracking-normal text-muted-foreground">Better context<br />Better understanding<br />Better decisions</p></div><div className="border-t border-border pt-5"><strong className="text-muted-foreground">CREATE VISIBILITY</strong><p className="mt-4 text-left normal-case leading-6 tracking-normal text-muted-foreground">Needs become visible<br />Capabilities become visible<br />People become discoverable</p></div></div>
      <span className="mt-8 h-8 w-px bg-border" /><span className="border border-border px-5 py-3">NEW CONNECTIONS</span><div className="mt-5 flex flex-wrap justify-center gap-3 text-muted-foreground"><span>EXPERTISE</span><span>CAPITAL</span><span>PARTNERSHIP</span></div>
    </div><figcaption id="outcomes-caption" className="mx-auto mt-8 max-w-xl text-center text-sm leading-6 text-muted-foreground">Capacity is the primary work. Visibility and new connections are valuable consequences of better understanding.</figcaption>
  </figure>
}

function EcosystemDiagram() {
  return <figure className="border-y border-border/70 py-10" aria-labelledby="ecosystem-caption"><div className="mx-auto max-w-3xl text-center font-mono text-[11px] uppercase tracking-[0.14em]"><strong className="inline-block border border-foreground px-5 py-3">AKSOS</strong><div className="mx-auto h-8 w-px bg-border" /><div className="grid gap-8 md:grid-cols-2"><div className="border-t border-border pt-5"><strong>ATIS</strong><p className="mt-3 text-foreground">UNDERSTAND<br />THE ENVIRONMENT</p><p className="mt-5 leading-7 text-muted-foreground">INFORMATION<br />EVIDENCE<br />ENTITIES<br />RELATIONSHIPS<br />CONTEXT</p></div><div className="border-t border-border pt-5"><strong>BATANA</strong><p className="mt-3 text-foreground">PARTICIPATE<br />IN THE ENVIRONMENT</p><p className="mt-5 leading-7 text-muted-foreground">PEOPLE<br />ORGANIZATIONS<br />CAPABILITIES<br />OPPORTUNITIES<br />CONNECTIONS</p></div></div><div className="mx-auto mt-8 h-8 w-px bg-border" /><span id="ecosystem-caption" className="inline-block border border-border px-5 py-3">GREATER POSSIBILITY</span></div><figcaption className="sr-only">AKSOS develops ATIS to understand the environment and Batana to explore participation in it.</figcaption></figure>
}

export default function AboutPage() {
  return <><SiteHeader /><main className="overflow-hidden pt-24">
    <section className="mx-auto max-w-6xl px-6 pb-28 pt-20 md:pb-40 md:pt-32"><Label>About Aksos</Label><h1 className="mt-8 max-w-5xl text-balance text-5xl font-medium leading-[0.98] tracking-[-0.06em] md:text-8xl">Some problems begin with a lack of information.</h1><p className="mt-16 max-w-4xl text-3xl leading-tight tracking-[-0.03em] text-muted-foreground md:ml-[16%] md:text-5xl">Ours began with having too much of it.</p><p className="mt-12 max-w-xl text-base leading-7 text-muted-foreground md:ml-[16%]">Information is everywhere. The difficult part is understanding what it belongs to, what it connects to, who it affects and what it might mean.</p></section>
    <section className="border-y border-border/70"><div className="mx-auto max-w-6xl px-6 py-24 md:py-32"><Label>The Question</Label><h2 className="mt-8 max-w-4xl text-4xl leading-tight tracking-[-0.05em] md:text-7xl">Why can an environment contain so much information and still be so difficult to understand?</h2><p className="mt-12 max-w-xl text-lg leading-8 text-muted-foreground">That question sits underneath AKSOS. It did not arrive as a perfectly planned idea. It accumulated through work, observation and conversations.</p></div></section>
    <section className="mx-auto max-w-6xl px-6 py-24 md:py-32"><Label>The Experience</Label><div className="mt-16 grid gap-20 md:grid-cols-[0.7fr_1.3fr] md:gap-32"><div className="font-mono text-xs uppercase tracking-[0.16em] text-muted-foreground">CIVA<br /><span className="my-8 block text-foreground">↓</span>The environment changed.<br /><span className="my-8 block text-foreground">↓</span>Then came the conversations.</div><div className="flex flex-col gap-16 text-lg leading-8 text-muted-foreground"><div><h3 className="mb-5 text-3xl tracking-[-0.04em] text-foreground">CIVA</h3><p>Tino contributed hands-on to work that broke complex public-sector systems into their underlying components. He helped structure information, build datasets and understand relationships between entities and systems, making fragmented public information more usable.</p></div><Rule /><div><h3 className="mb-5 text-3xl tracking-[-0.04em] text-foreground">Africa</h3><p>Work with nonprofits in Africa, including ACTIVE Ministry, revealed a different view of a familiar distance. Local knowledge, capability, ambition and institutional work already existed; information, organizations, expertise, investment, projects and people did not always find one another.</p></div><Rule /><div><h3 className="mb-5 text-3xl tracking-[-0.04em] text-foreground">Zimbabwe</h3><p>Conversations with professionals working within ministries and institutions in Zimbabwe added another necessary perspective. The people inside a system understand things that cannot always be learned from the outside. Public datasets can show signals, but not the whole institutional reality.</p></div></div></div></section>
    <section className="mx-auto max-w-6xl px-6 pb-24 md:pb-32"><ProblemDiagram /><div className="mx-auto max-w-3xl py-24"><Label>The Realization</Label><h2 className="mt-8 text-4xl leading-tight tracking-[-0.05em] md:text-6xl">The information exists. The connections are harder to see.</h2><div className="mt-10 grid gap-6 text-lg leading-8 text-muted-foreground md:grid-cols-2"><p>A regulation can be read without understanding everyone it affects. An investment can be announced without understanding where its consequences will travel.</p><p>A person can have the expertise required to solve a problem without ever discovering that the problem exists. Understanding begins when relationships become visible.</p></div></div></section>
    <section className="bg-foreground text-background"><div className="mx-auto max-w-6xl px-6 py-24 md:py-36"><Label>Our Mission</Label><h2 className="mt-8 max-w-5xl text-4xl leading-[1.05] tracking-[-0.06em] md:text-7xl">Make complex environments easier to see, understand and participate in.</h2><p className="mt-12 max-w-2xl text-lg leading-8 opacity-70">AKSOS is exploring how information, evidence, entities, relationships, context and perspective can form a connected picture. Not only what happened, but what it connects to, who it affects, what changed, what remains uncertain and where people might meaningfully participate.</p></div></section>
    <section className="mx-auto max-w-6xl px-6 py-24 md:py-32"><div className="grid gap-16 md:grid-cols-2"><div><Label>Our Vision</Label><h2 className="mt-8 text-4xl leading-tight tracking-[-0.05em] md:text-6xl">A world where complexity does not prevent participation.</h2></div><p className="max-w-xl text-lg leading-8 text-muted-foreground md:pt-12">We want to move toward environments where relationships can be discovered, evidence can be traced and perspective matters. Where people can see not only what is happening, but where they might fit within it.</p></div><div className="mt-24"><OutcomesDiagram /></div></section>
    <section className="border-y border-border/70"><div className="mx-auto max-w-6xl px-6 py-24 md:py-32"><Label>Why Africa</Label><div className="mt-12 grid gap-12 md:grid-cols-2"><div className="text-3xl leading-tight tracking-[-0.04em]">Africa is not one market, one economy or one problem.</div><div className="text-lg leading-8 text-muted-foreground"><p>Across many developing environments, significant work is underway around digital infrastructure, investment, skills, institutional capacity and economic development. The ambition, organizations, expertise and people exist. Yet these things do not always find one another.</p><p className="mt-8">AKSOS is interested in what happens when environments become easier to understand—and when that understanding makes participation easier, without promising certainty or guaranteed access.</p></div></div><div className="mt-20"><EcosystemDiagram /></div></div></section>
    <section className="mx-auto max-w-6xl px-6 py-24 md:py-32"><Label>The Work</Label><div className="mt-12 grid gap-10 md:grid-cols-2"><article className="border-t border-border pt-8"><h2 className="text-4xl tracking-[-0.05em]">See the environment.</h2><p className="mt-6 text-lg leading-8 text-muted-foreground">ATIS is being built to help people investigate relationships between information, entities, events, evidence and environments. Its purpose is to make those relationships easier to investigate and understand.</p><Link href="/atis" className="mt-8 inline-block font-mono text-xs uppercase tracking-[0.16em] underline underline-offset-8">Explore ATIS →</Link></article><article className="border-t border-border pt-8"><h2 className="text-4xl tracking-[-0.05em]">Find your place within it.</h2><p className="mt-6 text-lg leading-8 text-muted-foreground">Batana explores what becomes possible when people, organizations, capabilities, interests and opportunities become more discoverable to one another. Sometimes the first step is making yourself visible to the right environment.</p><Link href="/participate" className="mt-8 inline-block font-mono text-xs uppercase tracking-[0.16em] underline underline-offset-8">Explore Batana →</Link></article></div></section>
    <section className="border-y border-border/70"><div className="mx-auto max-w-6xl px-6 py-24 md:py-32"><Label>We Are Still Building.</Label><h2 className="mt-8 max-w-4xl text-4xl tracking-[-0.05em] md:text-6xl">This is not a finished answer.</h2><p className="mt-10 max-w-2xl text-lg leading-8 text-muted-foreground">We are researching it. Prototyping systems. Testing assumptions. Learning from real environments. Some parts of the vision already exist as working systems. Others are still being developed. We would rather show what we are learning than pretend we have already solved the problem.</p></div></section>
    <section className="mx-auto grid max-w-6xl gap-12 px-6 py-24 md:grid-cols-[1fr_1fr] md:items-center md:gap-20 md:py-32"><div className="relative aspect-[4/5] overflow-hidden bg-secondary"><Image src={HEADSHOT_URL} alt="Tino Makiriyado wearing glasses and a suit" fill sizes="(max-width: 768px) 100vw, 50vw" className="object-cover object-center grayscale" priority /></div><div><Label>The Person Behind The Question</Label><h2 className="mt-8 text-4xl tracking-[-0.05em] md:text-6xl">Tino Makiriyado</h2><div className="mt-8 flex flex-col gap-6 text-lg leading-8 text-muted-foreground"><p>AKSOS began with a question I encountered while working across very different environments: why can an environment contain so much information and still be so difficult to understand?</p><p>My work with CIVA gave me one perspective—breaking complex systems down, helping structure information and contributing to datasets that made relationships within those systems easier to understand. Work with nonprofits in Africa, including ACTIVE Ministry, and conversations with professionals working within Zimbabwean institutions gave me another.</p><p>The environments were different. The problem was surprisingly familiar.</p><p className="text-foreground">The information existed. The connections were harder to see.</p></div><div className="mt-10 flex flex-wrap gap-6"><a href={tinoLinkedInUrl || '/participate'} target={tinoLinkedInUrl ? '_blank' : undefined} rel={tinoLinkedInUrl ? 'noreferrer' : undefined} className="border border-foreground px-5 py-3 font-mono text-xs uppercase tracking-[0.14em]">Connect with Tino {tinoLinkedInUrl ? '(opens externally)' : '→'}</a><Link href="/participate" className="px-1 py-3 font-mono text-xs uppercase tracking-[0.14em] underline underline-offset-8">I have a perspective to add →</Link></div></div></section>
    <section className="bg-secondary"><div className="mx-auto max-w-6xl px-6 py-24 md:py-36"><Label>This Is An Open Invitation.</Label><h2 className="mt-8 max-w-4xl text-5xl leading-[0.98] tracking-[-0.06em] md:text-8xl">You may know something we don&apos;t.</h2><p className="mt-12 max-w-2xl text-lg leading-8 text-muted-foreground">You may work in digital infrastructure, inside government, in research, investment, technology or an organization in Africa. You may have access to data or have encountered a problem that deserves to be understood better. You do not have to know exactly where you fit. Start with a conversation.</p><div className="mt-10 flex flex-wrap gap-6"><Link href="/participate" className="bg-foreground px-5 py-3 font-mono text-xs uppercase tracking-[0.14em] text-background">Talk to Tino →</Link><Link href="/atis" className="px-1 py-3 font-mono text-xs uppercase tracking-[0.14em] underline underline-offset-8">Explore the work →</Link></div></div></section>
    <section className="mx-auto max-w-6xl px-6 py-24 md:py-36"><h2 className="max-w-5xl text-4xl leading-tight tracking-[-0.05em] md:text-7xl">AKSOS began with one question.<br /><span className="text-muted-foreground">We want to see how far it can go when more people begin asking it with us.</span></h2></section>
  </main><SiteFooter /></>
}
